{
 "title": "Жировки",
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "Адрес",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"invoice\",\n    tag: \"address\",\n    predicate: (r) => true,\n    start: -10y\n)"
   }
  ]
 },
 "panels": [
  { "title": "Квартира", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Итого начислено",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Рубли" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and r._field == \"total_accrued\")\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Услуги стоимость",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Рубли" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field =~ /.*_total$/))\r\n  |> filter(fn: (r) => r[\"type\"] == \"service\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Дополнительные  услуги стоимость",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Рубли" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field =~ /.*_value$/))\r\n  |> filter(fn: (r) => r[\"type\"] == \"extra_service\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Расход воды",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Кубометры" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"cold_water_diff\" or r._field == \"hot_water_diff\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Тарифы услуг",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Рубли" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field =~ /.*_rate$/))\r\n  |> filter(fn: (r) => r[\"type\"] == \"service\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Расход по услугам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Объем / количество" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field =~ /.*_value$/))\r\n  |> filter(fn: (r) => r[\"type\"] == \"service\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Дом", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Расход воды",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Кубометры" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_hot_water_count\" or r._field == \"house_cold_water_count\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Расход электроэнергии",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "string", "label": "кВт*ч" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_energy_lift\" or r._field == \"house_energy\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Площадь",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "string", "label": "м2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_square\" or r._field == \"house_sub_square\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Количество используемых в расчете прочих жилищно-коммунальных услуг зарегистрированных по месту жительства",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "м2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_people_other\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Общедомовое горячее водоснабжение (подогрев воды)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Гкал" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_hot_water_cal\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Количество используемых в расчете возмещения расходов по электроэнергии, потребляемой на работу лифтов, зарегистрированных по месту жительства",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "м2" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"invoice\")\r\n  |> range(start: -10y)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"house_invoice\" and (r._field == \"house_people_energy\"))\r\n  |> filter(fn: (r) => r[\"type\"] == \"simple\")\r\n  |> filter(fn: (r) => r[\"address\"] == \"${address}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}