{
 "title": "Жировки",
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "Адрес",
    "query": "SELECT DISTINCT address\nFROM invoices"
   }
  ]
 },
 "panels": [
  { "title": "Квартира", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Итого начислено",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  total_accrued\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Расход воды",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  cold_water_diff,\n  hot_water_diff\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Дополнительные  услуги стоимость",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    se.title,\n    se.value\nFROM invoices AS i\n         JOIN invoices_services_extra AS se ON se.invoice_id = i.id\nWHERE i.address = \"$address\"\n  AND $__timeFilter(i.date_invoice)\nORDER BY i.date_invoice"
    }
   ]
  },
  {
   "title": "Расход по услугам",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    s.title,\n    s.volume\nFROM invoices AS i\n         JOIN invoices_services AS s ON s.invoice_id = i.id\nWHERE i.address = \"$address\"\n  AND $__timeFilter(i.date_invoice)\nORDER BY i.date_invoice"
    }
   ]
  },
  {
   "title": "Услуги стоимость",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    s.title,\n    s.total\nFROM invoices AS i\n    JOIN invoices_services AS s ON s.invoice_id = i.id\nWHERE i.address = \"$address\"\n  AND $__timeFilter(i.date_invoice)\nORDER BY i.date_invoice"
    }
   ]
  },
  {
   "title": "Тарифы услуг",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    s.title,\n    s.rate\nFROM invoices AS i\n         JOIN invoices_services AS s ON s.invoice_id = i.id\nWHERE i.address = \"$address\"\nORDER BY i.date_invoice;"
    }
   ]
  },
  {
   "title": "Разница расхода по услугам",
   "type": "bargauge",
   "description": "Разница последней жировки к предыдущей",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    i.date_invoice AS \"time\",\r\n    s.title,\r\n    s.volume - (SELECT s2.volume\r\n              FROM invoices AS i2\r\n                       LEFT JOIN invoices_services AS s2 ON s2.invoice_id = i2.id\r\n              WHERE i.address = i2.address\r\n                  AND s.title = s2.title\r\n                  AND i.id != i2.id\r\n              ORDER BY i2.id DESC\r\n              LIMIT 1) AS rate\r\nFROM invoices AS i\r\n         JOIN invoices_services AS s ON s.invoice_id = i.id\r\nWHERE i.address = \"$address\"\r\n    AND  i.id = (SELECT MAX(i2.id)\r\n                    FROM invoices AS i2\r\n                    WHERE i.address = i2.address)\r\nORDER BY i.date_invoice;"
    }
   ]
  },
  {
   "title": "Разница стоимости услуг",
   "type": "bargauge",
   "description": "Разница последней жировки к предыдущей",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    s.title,\n    s.total - (SELECT s2.total\n               FROM invoices AS i2\n                        LEFT JOIN invoices_services AS s2 ON s2.invoice_id = i2.id\n               WHERE i.address = i2.address\n                       AND s.title = s2.title\n                       AND i.id != i2.id\n               ORDER BY i2.id DESC\n               LIMIT 1) AS total\nFROM invoices AS i\n         JOIN invoices_services AS s ON s.invoice_id = i.id\nWHERE i.address = \"$address\"\n        AND i.id = (SELECT MAX(i2.id)\n                    FROM invoices AS i2\n                    WHERE i.address = i2.address)\nORDER BY i.date_invoice;"
    }
   ]
  },
  {
   "title": "Разница тарифов услуг",
   "type": "bargauge",
   "description": "Разница последней жировки к предыдущей",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    i.date_invoice AS \"time\",\n    s.title,\n    s.rate - (SELECT s2.rate\n               FROM invoices AS i2\n                        LEFT JOIN invoices_services AS s2 ON s2.invoice_id = i2.id\n               WHERE i.address = i2.address\n                       AND s.title = s2.title\n                       AND i.id != i2.id\n               ORDER BY i2.id DESC\n               LIMIT 1) AS rate\nFROM invoices AS i\n         JOIN invoices_services AS s ON s.invoice_id = i.id\nWHERE i.address = \"$address\"\n        AND i.id = (SELECT MAX(i2.id)\n                    FROM invoices AS i2\n                    WHERE i.address = i2.address)\nORDER BY i.date_invoice;"
    }
   ]
  },
  { "title": "Дом", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Людей зарегистрировано ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_people\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Расход воды",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_cold_water_count,\n  house_hot_water_count\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Расход электроэнергии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_energy_lift,\n  house_energy\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Количество людей оплачивающих работу лифтов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_people_energy\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Горячее водоснабжение (подогрев воды)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_hot_water_cal\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  },
  {
   "title": "Площадь",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_invoice AS \"time\",\n  house_square,\n  house_sub_square\nFROM invoices\nWHERE address = \"$address\"\n AND  $__timeFilter(date_invoice)\nORDER BY date_invoice"
    }
   ]
  }
 ]
}